### ISSUE TITLE
NO data for the UI SEA, Ethernet (Shared and Physical) Adapters Traffic Analysis

### ISSUE THREAD

**Issue by dperry811** [guilhemmarchand/nmon-for-splunk#105]
I have two VIO Servers running AIX 6100-09-06-1543 and the ios level 2.2.5.20

here is the output on my adapters:
# lsdev -Cc adapter
ent0      Available 02-00 PCIe2 4-Port Adapter (10GbE SFP+) (e4148a1614109304)
ent1      Available 02-01 PCIe2 4-Port Adapter (10GbE SFP+) (e4148a1614109304)
ent2      Available 02-02 PCIe2 4-Port Adapter (1GbE RJ45) (e4148a1614109404)
ent3      Available 02-03 PCIe2 4-Port Adapter (1GbE RJ45) (e4148a1614109404)
ent4      Available 03-00 PCIe2 4-Port Adapter (10GbE SFP+) (e4148a1614109304)
ent5      Available 03-01 PCIe2 4-Port Adapter (10GbE SFP+) (e4148a1614109304)
ent6      Available 03-02 PCIe2 4-Port Adapter (1GbE RJ45) (e4148a1614109404)
ent7      Available 03-03 PCIe2 4-Port Adapter (1GbE RJ45) (e4148a1614109404)
ent8      Available       Virtual I/O Ethernet Adapter (l-lan)
ent9      Available       Virtual I/O Ethernet Adapter (l-lan)
ent10     Available       Virtual I/O Ethernet Adapter (l-lan)
ent11     Available       Shared Ethernet Adapter
ent12     Available       Shared Ethernet Adapter
ent13     Available       Shared Ethernet Adapter
ent14     Available       VLAN

Couple of questions......

1. why doesnt any data populate on the dashboard UI SEA, Ethernet (Shared and Physical) Adapters Traffic Analysis?  Shouldnt I see ent11, ent12, and ent13? (attached photo)
![image](https://user-images.githubusercontent.com/34077603/33348241-75166912-d44a-11e7-8c85-3a5dde15da7f.png)

2.  when I open the UI NET, Network Inbound / Outbound Traffic dashboard the only interfaces I can select is ent14 (attached photo)

Everything else is great!

![vio_nmon](https://user-images.githubusercontent.com/34077603/33348184-32cdbd08-d44a-11e7-9e58-156501d8d649.PNG)

**Comment by guilhemmarchand** [comment]
Hello,

Thank you using the Nmon app ;-)

I can see that you've closed this issue already, did you find your answers ?

Cheers,

Guilhem

**Comment by guilhemmarchand** [comment]
Hello,

You have probably found your answer, so just in case:

- according to the nmon command help page from  IBM:

[https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.cmds4/nmon.htm](url)

You need to activate the SEA collection with the "-O" option, this is not the case by default within the TA-nmon:

```
-O | Includes the Shared Ethernet adapter (SEA) VIOS sections in the recording file.
-- | --

```
You can set this option on a per deployment basis using a "local/nmon.conf" or on a per server basis in "/etc/nmon.conf"

**The priority is:**

1. /etc/nmon.conf
2. $SPLUNK_HOME/etc/apps/TA-nmon/local/nmon.conf
3. $SPLUNK_HOME/etc/apps/TA-nmon/default/nmon.conf

I will log an enhancement request to show this information in the interfaces pages.

Regarding the NET interface, since the ent14 is the only VLAN interface, this makes sense that this is the only interface being visible.

Hope this helps.

Guilhem

**Comment by dperry811** [comment]
Is this great….I was on this path and that why I removed the thread…I could and should re-post it for informational purposes……

Thank you,

DP
